odmp:
  pulsar:
    namespace: ${pulsar_tenant:public/default}
    clusters: ${pulsar_clusters:standalone}
    admin:
      url: ${pulsar_admin_url:http://localhost:8076}
    client:
      url: ${pulsar_client_url:pulsar://localhost:6650}
  file:
    base-path: ${file_base_path:/}
  secret: ${odmp_secret:ODMP_SIGNING_SECRET_KEY_NOT_FOR_PRODUCTION_USE}

spring:
  data:
    mongodb:
      authentication-database: ${mongo_auth_db:admin}
      database: ${mongo_dataflow_db:odmp_dataflow}
      username: ${mongo_username:dataflow_user}
      password: ${mongo_password:secret}
      host: ${mongo_host:localhost}
      port: ${mongo_port:27027}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: opendmp-dataflow
            client-secret: ${odmp_dataflow_kc_secret:1c44cb7e-c232-4a01-b13c-2f36a390a4e6}
            scope: open-id

        provider:
          keycloak:
            issuer-uri: ${keycloak_url:http://localhost:8083}/auth/realms/odmp
            authorization-uri: ${keycloak_url:http://localhost:8083}/auth/realms/odmp/protocol/openid-connect/auth
            token-uri: ${keycloak_url:http://localhost:8083}/auth/realms/odmp/protocol/openid-connect/token
            user-info-uri: ${keycloak_url:http://localhost:8083}/auth/realms/odmp/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak_url:http://localhost:8083}/auth/realms/odmp/protocol/openid-connect/certs
            #user-name-attribute: preferred_username

      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak_url:http://localhost:8083}/auth/realms/odmp/protocol/openid-connect/certs


springdoc:
  api-docs:
    path: /dataflow_api/doc/api-docs
    enabled: ${swagger_enabled:true}
  swagger-ui:
    path: /dataflow_api/doc/swagger-ui.html


server:
  port: ${odmp_dataflow_port:8080}
