language: java
jdk:
  - openjdk11
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - env: TARGET=opendmp-dataflow
      language: python
    - env: TARGET=opendmp-processor

before_script: mvn install --file opendmp-common/pom.xml
script: mvn clean test --file $TARGET/pom.xml


