language: java
dist: bionic
jdk:
  - openjdk11
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - env: TARGET=opendmp-dataflow
    - env: TARGET=opendmp-processor;MVN_OPTS=-Dtest=!TestPythonExecutor
      python: "3.8"
      install: pip install jep

before_script: mvn install --file opendmp-common/pom.xml
script: mvn clean test --file $TARGET/pom.xml $MVN_OPTS


