language: java

jdk:
  - openjdk11
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - script: mvn clean test --file opendmp-dataflow/pom.xml
    - script: mvn clean test --file opendmp-processor/pom.xml

before_script: mvn install && mvn install --file opendmp-common/pom.xml


