language: java
dist: bionic
jdk:
  - openjdk11
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - env: TARGET=opendmp-dataflow
      script: mvn clean test --file opendmp-dataflow/pom.xml
    - env: TARGET=opendmp-processor
      python: "3.8"
      install: pip install jep
      script: mvn clean test --file opendmp-processor/pom.xml -Dtest=!TestPythonExecutor

before_script: mvn install --file opendmp-common/pom.xml
# script: mvn clean test --file $TARGET/pom.xml $MVN_OPTS


