# This is a docker-compose file meant to support local development (NOT for production use)
version: '3.7'

services:

  mongodb:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      DATAFLOW_DB_USERNAME: dataflow_user
      DATAFLOW_DB_PW: secret
    ports:
      - 27027:27017
    volumes:
      - ./mongo-data:/docker-entrypoint-initdb.d
      - mongo_dev_data:/data/db
    
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  keycloak:
    image: jboss/keycloak:10.0.2
    container_name: odmp_keycloak
    networks:
      - keycloak-net
    ports:
      - 8083:8080
      - 8443:8443
    depends_on:
      - auth-postgres
    volumes:
      - ./kc-data:/tmp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      DB_ADDR: auth-postgres
      DB_USER: keycloak
      DB_PASSWORD: secret
      DB_VENDOR: "POSTGRES"

  auth-postgres:
    image: 'postgres'
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    networks:
      - keycloak-net

  pulsar:
    image: apachepulsar/pulsar:2.6.0
    volumes:
      - pulsar_data:/pulsar/data
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - 8076:8080
      - 6650:6650
    command: bin/pulsar standalone

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.1.0
    ports:
      - "9527:9527"
    depends_on:
      - pulsar
    links:
      - pulsar
    volumes:
      - pulsar_data:/data
    environment:
      REDIRECT_HOST: "http://127.0.0.1"
      REDIRECT_PORT: "9527"
      DRIVER_CLASS_NAME: "org.postgresql.Driver"
      URL: "jdbc:postgresql://127.0.0.1:5432/pulsar_manager"
      USERNAME: "pulsar"
      PASSWORD: "pulsar"
      LOG_LEVEL: "DEBUG"

  haproxy:
    image: 'haproxy:2.1-alpine'
    network_mode: host
    volumes:
      - type: bind
        source: ./conf/dev/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    
    
volumes:
  auth_postgres_data:
    driver: local
  mongo_dev_data:
    driver: local
  pulsar_data:
    driver: local
    
networks:
  keycloak-net:

