odmp:
  pulsar:
    namespace: ${puslar_namespace:public/default}
    clusters: ${pulsar_clusters:standalone}
    admin:
      url: ${pulsar_admin_url:http://localhost:8076}
    client:
      url: ${pulsar_client_url:pulsar://localhost:6650}
  redis:
    host: ${redis_host:localhost}
    port: ${redis_port:6379}
  plugins-enabled: ${odmp_plugins_enabled}

  processor:
    instance-type: ${odmp_processor_service_instance_type:GENERAL}

  s3:
    endpoint: ${aws_s3_endpoint:""}
    region: ${aws_region:US_EAST_1}
    access-key: ${aws_access_key:minio_access_key}
    secret-key: ${aws_secret_key:minio_secret_key}

  elastic:
    host: ${ELASTIC_HOST:localhost}
    port: ${ELASTIC_PORT:9200}
    protocol: ${ELASTIC_PROTOCOL:http}

server:
  port: ${http_port:8080}
  max-http-header-size: 1024KB

camel:
  threadpool:
    pool-size: 20
    max-pool-size: 50
    max-queue-size: -1
    allow-core-thread-time-out: true
    rejected-policy: callerruns
  springboot:
    main-run-controller: true
  component:
    aws-s3:
      amazon-s3-client: s3Client
      bridge-error-handler: true

spring:
  cloud:
    consul:
      discovery:
        enabled: true
        instance-id: opendmp-processor-service:${random.value}
        register: false
  servlet:
    multipart:
      max-request-size: 2000MB

  main:
    web-application-type: none
  application:
    name: opendmp-processor-service

logging:
  level:
    org:
      springframework:
        web: WARN
    com:
      amazonaws:
        # Longstanding issue with camel S3 component sometimes causes the AWS S3Client
        # to spam the logs with warnings, so raise the log level to ERROR
        services.s3.internal: ERROR

