# An example of the simplest possible, single node deployment
# There is no redundancy here - only one mongo, one pulsar, redis, etc.
# Might be suitable for light-duty usage only - I use it for demos.
# Not secure - you'll want to change passwords, generate your own client keys, override and add SSL to haproxy, at least.
version: '3.7'

services:

  mongodb:
    image: mongo:4.2-bionic
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      DATAFLOW_DB_USERNAME: dataflow_user
      DATAFLOW_DB_PW: secret
    volumes:
      - ./mongo-data:/docker-entrypoint-initdb.d
      - mongo_dev_data_sn:/data/db
    
  keycloak:
    image: jboss/keycloak:10.0.2
    networks:
      - keycloak-net
      - default
    ports:
      - 8083:8080
      - 8443:8443
    depends_on:
      - auth-postgres
    volumes:
      - ./kc-data:/tmp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      DB_ADDR: auth-postgres
      DB_USER: keycloak
      DB_PASSWORD: secret
      DB_VENDOR: "POSTGRES"
      KEYCLOAK_IMPORT: /tmp/odmp_realm.json -Dkeycloak.profile.feature.upload_scripts=enabled

  auth-postgres:
    image: 'postgres'
    volumes:
      - auth_postgres_data_sn:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    networks:
      - keycloak-net

  pulsar:
    image: apachepulsar/pulsar:2.6.0
    volumes:
      - pulsar_data_sn:/pulsar/data
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: bin/pulsar standalone

  redis:
    image: 'redis:6-alpine'
    restart: unless-stopped
    ports:
      - 6379:6379

  haproxy:
    image: 'haproxy:2.1-alpine'
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./conf/dev/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg

  opendmp-ui:
    image: opendmp-ui:0.0.1
    restart: unless-stopped

  opendmp-dataflow:
    image: opendmp-dataflow:0.0.1-SNAPSHOT
    restart: unless-stopped
    environment:
      PULSAR_ADMIN_URL: "http://pulsar:8080"
      PULSAR_CLIENT_URL: "pulsar://pulsar:6650"
      MONGO_HOST: "mongodb"
      MONGO_PORT: 27017
      KEYCLOAK_URL: "http://keycloak:8080"
      ODMP_DATAFLOW_PORT: 8042
    
  opendmp-processor:
    image: opendmp-processor:0.0.1-SNAPSHOT
    restart: unless-stopped
    environment:
      PULSAR_ADMIN_URL: "http://pulsar:8080"
      PULSAR_CLIENT_URL: "pulsar://pulsar:6650"
      REDIS_HOST: "redis"
    volumes:
      - /odmp/data:/odmp/data
    
volumes:
  auth_postgres_data_sn:
    driver: local
  mongo_dev_data_sn:
    driver: local
  pulsar_data_sn:
    driver: local
    
networks:
  keycloak-net:

